@startuml

class Position {
    -Position(x: int , y: int, pathPosition: int)
    +comparePosition(aPosition: Position): boolean
    +moveFoward(stepsForward: int, pathSize: int): int
    +coordinates(): Dimension2D
}

@enduml