@startuml

[*] --> Active: start game

state result_of_energy <<fork>>
Active --> result_of_energy: fights against\na beast

result_of_energy --> Active: its energy\nis greater than 0
result_of_energy --> Tired: its energy is 0 or negative

Active --> [*] : The next turn\nyou can play again
Tired --> [*] : skips next turn
@enduml