@startuml
'https://plantuml.com/class-diagram

!include Effect.puml
!include Food.puml
!include NullEffect.puml
!include FinishLineEffect.puml
!include Beast.puml
!include Injury.puml
!include InitialEffect.puml


NullEffect ..|> Effect
Beast ..|> Effect
FinishLineEffect .|> Effect
Effect <|. Food
Effect <|.. Injury
Effect <|.. InitialEffect
@enduml