@startuml
/'
+increaseEnergyByFoodConsumption() :Energy
+increaseEnergyByNoviceRank() :Energy
+increaseEnergyBySemiSeniorRank() :Energy
+increaseEnergyBySeniorRank() :Energy
+spendEnergyForAnimalFightWithoutEquipment() :Energy
+spendEnergyForAnimalFightWithHelmet() :Energy
+spendEnergyForAnimalFightWithArmor() :Energy
+spendEnergyForAnimalFightWithSwordShield() :Energy
+spendEnergyForAnimalFightWithKey() :Energy
'/
interface EnergyCalculator {
    calculate(energy :Energy) :Energy   
}
EnergyCalculator <|.. AnimalFightWithHelmet
class AnimalFightWithHelmet {
    calculate(energy :Energy) :Energy   
}
EnergyCalculator <|.. AnimalFightWithArmor
class AnimalFightWithArmor {
    calculate(energy :Energy) :Energy
}
@enduml