@startuml
class Points {
    -amount :int
    +EnergyPoints(amount :int)
    +addEnergyPoints(energyPoints :EnergyPoints) :EnergyPoints
    +substractEnergyPoints(energyPoints :EnergyPoints) :EnergyPoints
}
@enduml