@startuml
!include Senior.plantuml
!include Rookie.plantuml
!include SemiSenior.plantuml
interface Rank {
    +energyFromExperience(amount: int): int
    +ascent(): Rank
}
Rookie .|> Rank
Rank <|.. SemiSenior
Rank <|. Senior
Rookie ..> SemiSenior
SemiSenior .> Senior



@enduml