@startuml
!include Senior.plantuml
!include Rookie.plantuml
!include SemiSenior.plantuml
abstract class Rank {
    +energyFromExperience(unaCantidad: Energy): Energy
    +ascent(): Rank
}
Rank <|-- Senior
Rank <|-- SemiSenior
Rank <|-- Rookie

@enduml