@startuml
!include ../Energy/Energy.plantuml

class SemiSenior {
    -shift: int
    +SemiSenior()
    +energyFromExperience(unaCantidad: Energy): Energy
    +ascent(): Rank
}
SemiSenior ..|> Energy
@enduml