@startuml
!include ../Equipment/Equipment.plantuml
!include Gladiator.plantuml
!include ../rank/Rank.plantuml
!include ../position/Position.plantuml
!include ../State/State.plantuml
!include ../game/TurnDecider.plantuml

Gladiator *-- Rank
Gladiator *-- Equipment
Gladiator *-- Position
Gladiator *- State
Gladiator ..> TurnDecider

@enduml