@startuml
class Gladiator {
    -name : String
    +Gladiator(): Gladiator
    +move(): int
    +drinkWine()
    +eat()
    +fightWithBeast()
    +upgrade()
    +gameOver()
    +getName(): String
    +injured()
    +getEnergy(): int
    +update()
    +runEffect()
    +positionate()
    +getIntoBacchanalia()
    +refreshState()
    +won(): GameState
    +decideIfPlaysAgain(turnDecider: TurnDecider, gladiatorTurn: int)
    +turnEnded(gladiatorTurn: int ): int
    +rest()
    +showEquipment(): String
}
@enduml