@startuml
class Gladiator {
    -win: boolean 
    -name : String
    +Gladiator(): Gladiator
    +move()
    +drinkWine()
    +eat()
    +fightWithBeast()
    +upgrade()
    +gameOver()
    +getName(): String
    +turn(): boolean
    +injured()
    +setInitialEnergy(Energy energy)
    +completeArmament(): boolean
    +getEnergy(): Energy
    +update()

}
@enduml