@startuml
class Gladiator {
    -name : String
    -ENERGY_FROM_FOOD: int
    +Gladiator(): Gladiator
    +move(): int
    +drinkWine()
    +eat()
    +fightWithBeast()
    +upgrade()
    +gameOver()
    +getName(): String
    +injured()
    +getEnergy(): int
    +update()
    +runEffect()
    +positionate()
    +getIntoBacchanalia()
    +refreshState()
    +won(): GameState
    +decideIfPlaysAgain(turnDecider: TurnDecider)
    +turnEnded(gladiatorTurn: int ): int
    +tryToWin(middlePosition: Position)
    +rest()
}
@enduml