@startuml
'https://plantuml.com/class-diagram
!include NullEquipment.plantuml
!include Helmet.puml
!include Armor.puml
!include ShieldSword.puml
!include Key.puml
/' !include ..\Energy\Energy.plantuml
!include ..\Gladiator\Gladiator.plantuml'/
Equipment ..|> NullEquipment
Equipment ..|> Helmet
Equipment ..|> Armor
Equipment ..|> ShieldSword
Equipment ..|> Key
/' Gladiator o-- Equipment '/

@enduml