@startuml
'https://plantuml.com/class-diagram
!include Equipment.plantuml
!include NullEquipment.plantuml
!include Helmet.plantuml
!include Armor.plantuml
!include ShieldSword.plantuml
!include Key.plantuml


NullEquipment .|> Equipment
NullEquipment .> Helmet
Equipment <|.. Helmet
Helmet .> Armor
Armor .> ShieldSword
Equipment <|.. Armor
Equipment <|.. ShieldSword
Key <.. ShieldSword
Equipment <|. Key

@enduml