@startuml
'https://plantuml.com/class-diagram
!include Equipment.plantuml
!include NullEquipment.plantuml
!include Helmet.plantuml
!include Armor.plantuml
!include ShieldSword.plantuml
!include Key.plantuml
!include ../State/State.plantuml

Equipment <|.. NullEquipment
Equipment <|.. Helmet
Equipment <|.. Armor
Equipment <|.. ShieldSword
Equipment <|.. Key

Equipment ..> State

@enduml