@startuml
!include Beast.plantuml
!include Bacchanalia.plantuml
!include Effect.plantuml
!include Injury.plantuml
!include NullEffect.plantuml
!include Upgrade.plantuml

Effect <|. Beast
Effect <|.. Bacchanalia
Injury ..|> Effect
Effect <|.. NullEffect
Upgrade .|> Effect

@enduml