@startuml
!include Square.plantuml
!include ../position/Position.plantuml
!include Effect.plantuml
!include ../Gladiator/Gladiator.plantuml

Square o-- Position
Square "2" o- Effect: contains
Square ..> Gladiator

@enduml