@startuml

autonumber

actor Actor

activate Actor
create Gladiator
Actor -> Gladiator : <<Create>> Gladiator()
activate Gladiator
    create Rank
    Gladiator -> Rank :  <<Create>> Rank() 
    create Energy
    Gladiator -> Energy : <<Create>> Energy(0)
    create Equipment
    Gladiator -> Equipment : <<Create>> Equipment()
    Create State
    Gladiator -> State : <<Create>> State()
deactivate Gladiator

Actor -> Gladiator : turn()
loop I represent its use 8 times in the use case
activate Gladiator
    Gladiator -> Gladiator : update()
    activate Gladiator

        Gladiator -> Rank : ascent()
        activate Rank
            Rank --> Gladiator : Rank
        deactivate Rank

        Gladiator -> Rank : energyFromExperience(this.energy)
        activate Rank
            Rank --> Gladiator : Energy()
        deactivate Rank
    
    deactivate Gladiator
    Gladiator -> State : move()
    activate State
    State --> Gladiator: int between 0 and 6
    deactivate State
    Gladiator --> Actor : int between 0 and 6
deactivate Gladiator
end loop

Actor -> Gladiator : getEnergy
activate Gladiator
Gladiator --> Actor : Energy()
deactivate Gladiator

Actor -> Energy : getPoints
activate Energy
Energy --> Actor : 5
deactivate Energy

deactivate Actor

@enduml