@startuml
autonumber
actor Actor
Actor --> Gladiator: <<create>> Gladiator()
Actor --> Gladiator: eat()
Actor --> Gladiator: getEnergy(): Energy
Gladiator -->> Actor: energy
Actor --> Energy: getPoints():int
Energy -->> Actor: energyPoints
@enduml