@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Actor
activate Actor

create collections Square
Actor -> Square: <<create>>
create EffectFactory
Actor -> EffectFactory: <<create>>
Actor -> Square: add(effectFactory.createEffect("NullEffect"),effectFactory.createEffect("NullEffect"), new Position(0,0,0))
Actor -> Square: add(effectFactory.createEffect("NullEffect"),effectFactory.createEffect("Comida"), new Position(1,0,1))
Actor -> Square: affect(Gladiator)

create collections Gladiator
Actor -> Gladiator: <<create>> Gladiator("Example")
activate Gladiator
    create State
    Gladiator -> State: <<create>>
deactivate Gladiator

create Game
Actor -> Game: getInstance(Gladiator, Square)

Actor -> Game: startGame()
activate Game
    create StateGame
    Game -> StateGame: <<Create>>
deactivate Game

Actor -> Game: playTurn(1)

Actor -> Game: playTurn(1)
activate Game
    Game -> StateGame: nextTurn(gladiators, Square, 1)
    activate StateGame
        StateGame -> Gladiator: move(path.size(), 1)
        activate Gladiator
            Gladiator -> Gladiator: update()
            Gladiator -> Gladiator: rest()
            Gladiator -> State: energyFromState(0)
            activate State
                State -> Gladiator: 5
            deactivate State
        deactivate Gladiator
    deactivate StateGame
deactivate Game

Actor -> Gladiator: getEnergy()
activate Gladiator
        Gladiator --> Actor: 5
deactivate Gladiator

deactivate Actor
@enduml