@startuml
autonumber
actor Actor
Actor -->> Gladiator: <<create>> Gladiator()
Actor -->> initialSquare: <<create>> Initial()
Actor -> initialSquare: receiveGladiator(gladiator: Gladiator)
activate initialSquare
deactivate initialSquare
Actor -> Gladiator: upgrade()
activate Gladiator
Actor -> Gladiator: upgrade()
Actor -> Gladiator: upgrade()
Actor -> Gladiator: upgrade()
Actor -> Gladiator: fightWithBeast()
Actor -> Gladiator: getEnergy(): Energy
Gladiator -->> Actor: energy
deactivate Gladiator
Actor -> Energy: getPoints():int
activate Energy
Energy -->> Actor: energyPoints
deactivate Energy
Actor -> Gladiator: upgrade()
activate Gladiator
Actor -> Gladiator: getEnergy(): Energy
Gladiator -->> Actor: energy
deactivate Gladiator
Actor -> Energy: getPoints():int
activate Energy
Energy -->> Actor: energyPoints
deactivate Energy
@enduml