@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Actor

activate Actor
Actor -> Gladiator: <<create>> Gladiator()
Actor -> Gladiator: upgrade()

activate Gladiator
    Gladiator -> Equipment: upgrade()   
    activate Equipment
        Equipment -> Equipment: upgrade()
        activate Equipment
        deactivate Equipment
        Equipment --> Gladiator: Equipment
    deactivate Equipment
deactivate Gladiator

Actor-> Gladiator: fightWithBeast()
activate Gladiator
    Gladiator -> Equipment: receiveAttack(this.Energy)
    activate Equipment
        Equipment->Energy: substract()
        activate Energy
            Energy --> Equipment: Energy
        deactivate Energy
        Equipment --> Gladiator: Energy
    deactivate Equipment
deactivate Gladiator

Actor -> Gladiator : getEnergy
activate Gladiator
    Gladiator --> Actor : Energy()
deactivate Gladiator


Actor -> Energy : getPoints
activate Energy
    Energy --> Actor : (Points:-15)
deactivate Energy

deactivate Actor
@enduml