@startuml
autonumber
actor Actor
Actor -->> Gladiator: <<create>> Gladiator()
Actor -> Gladiator: eat()
activate Gladiator
Actor -> Gladiator: getEnergy(): Energy
Gladiator -->> Actor: energy
deactivate Gladiator
Actor -> Energy: getPoints():int
activate Energy
Energy -->> Actor: energyPoints
deactivate Energy
@enduml