@startuml

autonumber

actor Actor

activate Actor

Actor -> Gladiator : <<Create>> Gladiador()
activate Gladiator
    Gladiator -> Rank :  <<Create>> 
    Gladiator -> State : <<Create>> 
deactivate Gladiator

loop I represent its use 7 times in the use case
Actor -> Gladiator : move(10,1)
end loop

Actor -> Gladiator : move(10,1)
activate Gladiator
    Gladiator -> Rank: ascent()
    activate Rank
        Rank --> Gladiator: SemiSenior
    deactivate Rank

    Gladiator -> Rank: energyFromExperience(20)
    activate Rank
        Rank --> Gladiator: 25
    deactivate Rank

    Gladiator -> State: move(1)
    activate State
        State --> Gladiator: 8
    deactivate State
    Gladiator -> Position: moveFoward(0, Square.size())
    activate Position
        Position --> Gladiator: 8
    deactivate Position
    Gladiator --> Actor: 8
deactivate Gladiator

Actor -> Gladiator: getEnergy()
activate Gladiator
    Gladiator --> Actor: 25
deactivate Gladiator
deactivate Actor

@enduml