@startuml

autonumber
actor Actor

activate Actor

create StateGame
Actor -> StateGame: <<Create>>
create collections Square
Actor -> Square: <<create>>
create EffectFactory
Actor -> EffectFactory: <<create>>
Actor -> Square: add(effectFactory.createEffect("NullEffect"),\neffectFactory.createEffect("Comida"), new Position(0,0,0))
Actor -> Square: add(effectFactory.createEffect("NullEffect"),\neffectFactory.createEffect("NullEffect"), new Position(1,0,1))
Actor -> Square: add(effectFactory.createEffect("NullEffect"),\nnew FinishLineEffect(), new Position(2,0,2))

create collections Gladiator
Actor -> Gladiator: <<create>>
Actor -> Gladiator: add(new Gladiator("Example"))

create Game
Actor -> Game: getInstance(Gladiator, Square, new Dice())

Actor -> Game: startGame()

loop Until the Finalized method returns true
Actor -> Game: playTurn(1)
activate Game
    Game --> Actor: StateGame
deactivate Game
end loop

Actor -> StateGame: result(Gladiator)
activate StateGame
    StateGame --> Actor: false
deactivate StateGame

deactivate Actor

@enduml