@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Actor

activate Actor

create Gladiator
Actor -->> Gladiator: <<create>> Gladiator("Example")
activate Gladiator
    create Equipment
    Gladiator -> Equipment: <<create>>
deactivate Gladiator

Actor -> Gladiator: upgrade()
activate Gladiator
    Gladiator -> Equipment: upgrade()
    activate Equipment
        Equipment -> Gladiator: new Helmet()
    deactivate Equipment
deactivate Gladiator

Actor -> Gladiator: fightWithBeast()
activate Gladiator
    Gladiator -> Equipment: receiveAttack(this.energy)
    activate Equipment
        Equipment --> Gladiator: 5
    deactivate Equipment
deactivate Gladiator

Actor -> Gladiator: getEnergy()
activate Gladiator
    Gladiator --> Actor: 5
deactivate Gladiator

deactivate Actor
@enduml