@startuml
!include ActiveGame.plantuml
!include FinishedByWinning.plantuml
!include FinishedByTurns.plantuml
!include GameState.plantuml
!include ../Gladiator/Gladiator.plantuml
!include ../square/Square.plantuml

GameState <|... FinishedByWinning
GameState <|.. ActiveGame
GameState <|.. FinishedByTurns
GameState .> "2..6" Gladiator
GameState ..> "*" Square

@enduml