@startuml
interface GameState {
    +nextTurn(gladiators: ArrayList<Gladiator> ,path: ArrayList<Square> , diceResult: int , gladiatorTurn: int ): GameState
    +Finalized(): boolean
    +result(gladiators: ArrayList<String>): boolean
    +turnEnded(gladiatorTurn: int, gladiators: ArrayList<Gladiator> ): int
    +entryOfTheGladiatorToTheFirstSquare(gladiators: ArrayList<Gladiator> ,path: ArrayList<Square> )
    +defeat(): GameState
}
@enduml