@startuml
class Game {
    -turns: int
    -MAX_TURNS_IN_A_GAME: int
    -NEXT_GLADIATOR_TO_PLAY: int
    -Game(ArrayList<Gladiator> gladiators, ArrayList<Square> path, Dice dice)
    +getInstance(): Game
    +getPath(): ArrayList<Square>
    +getInstance(ArrayList<Gladiator> gladiators, ArrayList<Square> path, Dice dice): Game
    +startGame(): boolean
}
@enduml