@startuml
!include ../Dice/dice.plantuml
class Active{
    +move(): Int
    +update(): State
    +runEffect(Effect effect, Gladiator gladiator)
    +fracture(): State
    +getIntoBacchanalia(Gladiator aGladiator): State
}

Active --> Dice
@enduml