@startuml
!include ../Dice/dice.plantuml
class Active{
    +move(): Int
    +update(): State
    +runEffect(effect: Effect, gladiator: Gladiator)
    +fracture(): State
    +getIntoBacchanalia(aGladiator: Gladiator ): State
}

Active --> Dice
@enduml