@startuml
abstract State {
    +move(): Int
    +update(int energy):State
    +runEffect(Effect effect, Gladiator gladiator)
    +fracture(): State
    +getIntoBacchanalia(Gladiator aGladiator): State
    +isWinner(): GameState
    +decideIfPlaysAgain(TurnDecider turnDecider)
    +tryToWin(Gladiator aGladiator, Position middlePosition)
    +updateTurn(int turn): int
}   
@enduml