@startuml
!include Active.plantuml
!include Tired.plantuml
!include State.plantuml
!include Injured.plantuml
!include Winner.plantuml
!include InTheBacchanalia.plantuml
!include ../square/Effect.plantuml
!include ../position/Position.plantuml
!include ../game/TurnDecider.plantuml

State <|-- Active
State <|-- Tired
State <|-- Injured
State <|-- InTheBacchanalia
Winner --|> State
State .> Effect
State .> TurnDecider
Position <. State

@enduml